### ISSUE TITLE
SegFault in FileWriter::write()

### ISSUE THREAD

**Issue by glaurung24** [dafer45/TBTK#2] opened 2016-10-19 16:56 UTC
If FileWriter::write is called with a file path set to a directory, which doesn't exist, a SegFault is raised.

**Comment by dafer45** [comment] 2018-07-28 09:06
The FileWriter is being phased out in favor of serialization. Rather than making the path argument work, this issue therefore has been resolved by printing an error message if a non default path value is passed to the function. The issue is resolved by commit 8f47b88.

The decision to not support the path argument may be revised in the future if the FileWriter turns out to become more important.

**Closed as completed by dafer45** 2018-07-28 09:06 UTC
